Clean up macOS CI uninstall list
Inochi2D/inochi-creator pull request #102
Opened 2022-10-07 05:15 UTC by tellowkrinkle

Just makes the list of packages to remove a little cleaner looking

Using brew to uninstall harfbuzz worked fine, and most of the packages didn't seem to be getting referenced by anything.  It seems to still build, and runs fine on x86, but I don't have an arm Mac to test that.

Also adds a space to the `CFBundleName` entry in the `Info.plist`, which is what shows up in the menubar when the application is running.  You'd think macOS would use the `CFBundleDisplayName` for that but it doesn't.

2022-10-07 05:17 UTC, LunaTheFoxgirl commented on .github/workflows/nightly.yml
> +        brew remove --ignore-dependencies freetype harfbuzz libpng brotli
When I earlier tried making brew remove harfbuzz the CI failed with the error that harfbuzz was not installed.

2022-10-07 05:18 UTC, LunaTheFoxgirl commented on .github/workflows/nightly.yml
> +        brew remove --ignore-dependencies freetype harfbuzz libpng brotli
see https://github.com/Inochi2D/inochi-creator/actions/runs/3179298771/jobs/5181643488

2022-10-07 05:19 UTC, LunaTheFoxgirl commented
Due to the issue I've pointed out in the comment, I'd like the portion that simplifies the script removed for now, it's too close to release for me to get in to a spiral of trying to debug and minimize the issues when the current thing works.

2022-10-07 05:29 UTC, tellowkrinkle commented
Okay, I moved that part to #103

2022-10-07 05:36 UTC, tellowkrinkle commented on .github/workflows/nightly.yml
> +        brew remove --ignore-dependencies freetype harfbuzz libpng brotli
Hmm, I can't can't seem to reproduce it even with the exact same script https://github.com/tellowkrinkle/inochi-creator/actions/runs/3202454634/jobs/5231453673

I'm guessing it's GitHub messing with the package list in their CI image.  They seem to like to do that.  They recently un-preinstalled libjpeg which broke PCSX2's CI script for a bit.  One possibility is to `brew remove` each package separately and ignore errors with `|| true`, which is [what we now do in PCSX2](https://github.com/PCSX2/pcsx2/commit/8b375d66fae12022e3f5853d1a59dc39e98ae9f6).

2022-10-07 17:25 UTC, LunaTheFoxgirl requested changes

2022-10-07 17:25 UTC, LunaTheFoxgirl commented on .github/workflows/nightly.yml
> +          brew remove --ignore-dependencies "$package" || true
Even if the package is "removed" from their package list the files may still be there so we'd probably want to manually try to delete the files in case brew remove doesn't find them

2022-10-08 07:18 UTC, tellowkrinkle commented on .github/workflows/nightly.yml
> +          brew remove --ignore-dependencies "$package" || true
The package is still in brew's list of existing packages, it's just not installed
Yeah I know the error message doesn't make it sound that way, but that's just Homebrew being fun.  If the package wasn't in the registry, it would say `Error: No available formula with the name "harfbuzz"`

Maybe I should change the wording of the comment though

2023-09-16 18:51 UTC, closed without merging