Path deform tool update.
Inochi2D/inochi-creator pull request #312
Opened 2023-08-27 15:32 UTC by seagetch

Added bunch of changes to path deform tool.

1. Partial deformation for selected vertices.
     Path deformation tool can select vertices when pressing Alt key. When applying deformation, only selected vertices are moved.

2. Update undo / redo of path deformation tool.
     Redo / undo of Path deformation tool remembers the keypoint of the mesh editor.

3. Partial reset / flipping
     When selecting vertices, right click menu shows "Reset selected" and "Flip selected horizontally from mirror" on the menu. It applies the reset / flip of the deformation only to the selected vertices.

2023-08-28 14:04 UTC, LunaTheFoxgirl requested changes
We should keep the code style consistent, otherwise this commit is almost ready to merge.

2023-08-28 14:04 UTC, LunaTheFoxgirl commented on source/creator/utils/transform.d
> +void autoFlipBinding(ParameterBinding binding, ParameterBinding srcBinding, vec2u index, uint axis, bool extrapolation = true, ulong[]* selected = null) {
Freestanding functions should use the inc<Space><Function Name> convention.

In this case incBindingAutoFlip

2023-08-28 14:04 UTC, LunaTheFoxgirl commented on source/creator/utils/transform.d
> +ParameterBinding getPairBindingFor(Parameter param, Node target, FlipPair pair, string name, bool forceCreate = false) {
See autoFlipBinding,

incBindingGetPairFor, would be appropriate here

2023-08-29 13:20 UTC, seagetch commented on source/creator/utils/transform.d
> +void autoFlipBinding(ParameterBinding binding, ParameterBinding srcBinding, vec2u index, uint axis, bool extrapolation = true, ulong[]* selected = null) {
renamed autoFlipBinding to incBindingAutoFlip.

2023-08-29 13:20 UTC, seagetch commented on source/creator/utils/transform.d
> +ParameterBinding getPairBindingFor(Parameter param, Node target, FlipPair pair, string name, bool forceCreate = false) {
renamed getPairBindingFor to incBindingGetPairFor.

2023-08-29 22:54 UTC, LunaTheFoxgirl approved these changes
LGTM, merging

2023-08-29 22:54 UTC, merged