Ask Save when Closing Project
Inochi2D/inochi-creator pull request #441
Opened 2024-09-23 05:14 UTC by r888800009

* resolves https://github.com/Inochi2D/inochi-creator/issues/145
* Allow users to configure exit behavior
* A window pops up when the project is closed, exited, or new.
  * NewProjectAskHandler, CloseAskHandler, ExitAskHandler
* Importing pop-up windows is currently not supported. I think `kra.d` and `psd.d` need to be refactored first.
  * https://github.com/nijigenerate/nijigenerate/pull/30
  * https://github.com/nijigenerate/nijigenerate/pull/29
* Pop-up window when "open" is not currently supported

2024-09-24 03:25 UTC, LunaTheFoxgirl requested changes
Wording should be fixed, but otherwise looks good.

2024-09-24 03:25 UTC, LunaTheFoxgirl commented on source/creator/io/save.d
> +            _("Would you like to save your changes before closing?\n\nYou can change the default behaviour in the settings."),
Maybe these should be reworded slightly;
Title should be "Save before quitting?"
Body should be "Would you like to save your changes before quitting?\n\nYou can change the default behaviour in the settings."

2024-09-24 03:25 UTC, LunaTheFoxgirl commented on source/creator/windows/settings.d
> +                            incTooltip(_("When closing a project, should it be saved automatically?"));
Wording should be: "Should changes be saved automatically when closing a project?"

2024-09-24 04:28 UTC, r888800009 commented on source/creator/io/save.d
> +            _("Would you like to save your changes before closing?\n\nYou can change the default behaviour in the settings."),
I think "closing" is more appropriate for various scenarios.

This window is used repeatedly when exiting, opening a new project, or closing an existing project.
Maybe we should change title to "Save before closing?"

2024-09-24 04:31 UTC, r888800009 commented on source/creator/io/save.d
> +            _("Would you like to save your changes before closing?\n\nYou can change the default behaviour in the settings."),
Or we can implement different windows for different cases

2024-09-27 23:13 UTC, LunaTheFoxgirl commented on source/creator/io/save.d
> +            _("Would you like to save your changes before closing?\n\nYou can change the default behaviour in the settings."),
Different windows for different cases seems like a lot of duplicated work.
This will do for now.

2024-09-27 23:14 UTC, LunaTheFoxgirl approved these changes

2024-09-27 23:14 UTC, merged