Duplication and atlas update
Inochi2D/inochi-creator pull request #466
Opened 2024-12-14 05:45 UTC by Hakazaba

Duplication now will be taken account of during the generation of the atlas. This may need an update of Inochi session to be compatible and needs testing.

There are some variables that may not be currently copied over. Someone more familiar with the functions of composites for instance, should look over the variables to make sure everything important is copied.

2024-12-14 14:39 UTC, LunaTheFoxgirl requested changes
Good work, however there's some cleanup to do before this can be merged.

2024-12-14 14:39 UTC, LunaTheFoxgirl commented on source/creator/actions/node.d
> +    if ((cast(Part) n) is null) {
Please follow the code-style used throughout the rest of Inochi2D, this is difficult to read.

2024-12-14 14:39 UTC, LunaTheFoxgirl commented on source/creator/actions/node.d
> +    {
This curlybrace should be on the same line as the foreach.

2024-12-14 14:39 UTC, LunaTheFoxgirl commented on source/creator/panels/nodes.d
> +                if((cast(Camera)n is null) & (cast(Puppet)n is null)){
This could be simplified to
```d
if (cast(Camera)n || cast(Puppet)n)
```

2024-12-14 14:52 UTC, Hakazaba commented on source/creator/panels/nodes.d
> +                if((cast(Camera)n is null) & (cast(Puppet)n is null)){
We only want to proceed if they're both null. If they aren't then we might end up trying to copy the puppet or camera.

2024-12-14 14:53 UTC, Hakazaba commented on source/creator/actions/node.d
> +    if ((cast(Part) n) is null) {
I'll try to clean it up a bit tomorrow

2024-12-14 14:56 UTC, LunaTheFoxgirl commented on source/creator/panels/nodes.d
> +                if((cast(Camera)n is null) & (cast(Puppet)n is null)){
In which case just do !cast; that will be a is-null check

2024-12-15 18:28 UTC, LunaTheFoxgirl approved these changes

2024-12-15 18:28 UTC, merged