Adds a flatpak workflow
Inochi2D/inochi-creator pull request #74
Opened 2022-09-14 22:56 UTC by orowith2os

This still needs a bit of work (namely, it needs to add metadata and a .desktop file to the manifest) but it should "work". It also might need a bit more work to automatically pull the latest numbered release of the archive, I'm still figuring that portion out.

2022-09-14 23:39 UTC, orowith2os commented
One more thing to consider would be leaving the releases to be on Flathub, as it would most likely be less work to maintain. But an app can be published both on Inochi's own repo, and on Flathub at the same time, and installed simultaneously. (Flatpak! Yay!)

2022-09-15 02:36 UTC, orowith2os commented
Hm, maybe better to split the workflow into its own repo, and toss the Inochi Session builder in there as well. I could, possibly, also make a shell script to run on that repo that updates the files and checksums on a new release automatically.

2022-09-15 15:02 UTC, LunaTheFoxgirl requested changes

2022-09-15 15:02 UTC, LunaTheFoxgirl commented on .github/workflows/flatpak.yml
> +    branches: [main]
Why are we running this on every push to main branch?
We should not be building new flatpaks every time I push something.

2022-09-15 15:02 UTC, LunaTheFoxgirl commented on .github/workflows/flatpak.yml
> +      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
Any specific reasons we're using "kde-5.15"?

2022-09-15 15:02 UTC, LunaTheFoxgirl commented on .github/workflows/flatpak.yml
> +    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
What will this do, will it put the flatpak manifest in the latest tag? if so then that's not exactly what we want.

2022-09-15 15:03 UTC, LunaTheFoxgirl commented
CI build failure for PRs is not due to compilation, so that one can be ignored for now.

2022-09-15 15:04 UTC, LunaTheFoxgirl commented
Additionally it appears that it's saying it's a "master" branch build, which is not true, our main branch is called `main`

![image](https://user-images.githubusercontent.com/7032834/190439090-537e0c2b-7355-4a3e-bafc-eb8e7e93426d.png)

2022-09-15 15:14 UTC, orowith2os commented on .github/workflows/flatpak.yml
> +    branches: [main]
Ah, yeah, I pretty much just copy pasted the example and made sure that it would hopefully work to build it. I'm not exactly sure on how to make it automatically build on every release, after the build-and-release workflow is done completely.

2022-09-15 15:16 UTC, orowith2os commented on .github/workflows/flatpak.yml
> +      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
There's just one, actually -- kdialog. It refuses to work in the standard freedesktop SDK, so I tossed the KDE one there and it worked. 

We can switch to the base fd.o SDK/Runtime when the kdialog dependency is removed (aka Creator uses portals instead of tinyfiledialogs when it sees a flatpak environment)

2022-09-15 15:17 UTC, orowith2os commented on .github/workflows/flatpak.yml
> +    branches: [main]
And as for detecting a flatpak environment, Flatpak supplies a .flatpak_info (I forget the specific file name) in the "root" filesystem for each flatpak. So looking for that file, and using the desktop portals if it's seen would work.

2022-09-15 15:17 UTC, LunaTheFoxgirl commented on .github/workflows/flatpak.yml
> +    branches: [main]
This should react to whenever any new _tags_ are pushed, aka. versions.
```yml
on:
  push:
    tags:
      - '*'
```

2022-09-15 15:18 UTC, LunaTheFoxgirl commented on .github/workflows/flatpak.yml
> +      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
I see, we really need an issue to keep track of getting portals implemented.

2022-09-15 15:18 UTC, orowith2os commented on .github/workflows/flatpak.yml
> +    branches: [main]
..ah, I seem to have posted my comments on the wrong review section. My bad.

2022-09-15 15:18 UTC, LunaTheFoxgirl commented on .github/workflows/flatpak.yml
> +    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
It creates an artifact I found out

2022-09-15 15:22 UTC, LunaTheFoxgirl commented
> One more thing to consider would be leaving the releases to be on Flathub, as it would most likely be less work to maintain. But an app can be published both on Inochi's own repo, and on Flathub at the same time, and installed simultaneously. (Flatpak! Yay!)

Does Flathub allow the kind of dual licensing we have between our branding assets and the BSD 2-clause app?

2022-09-15 15:31 UTC, orowith2os commented
I don't see why not. Their submission list asks if the icons and such are redistributable by any party, so they do have something there just to be sure.

Considering the icons and such, from my understanding, can be distributed freely with permission, I don't see much issue with it. You'd just need to allow flathub to distribute them.

2022-09-16 02:02 UTC, orowith2os commented
I'll sort out metadata and a desktop file tomorrow, hopefully it somewhat works now.

2022-10-09 04:02 UTC, LunaTheFoxgirl commented
This has moved to flathub, I'll close it for now and re-open if there's objections.

2022-10-09 04:02 UTC, closed without merging