Sort languages
Inochi2D/inochi-creator pull request #92
Opened 2022-10-04 01:34 UTC by hanss314

Sorts language alphabetically (by unicode). This should result in a mostly sensible order with similar scripts lumped together.

Also implements disambiguation of locales with identical names by specifying the source folder. This can be a pretty long path name sometimes, but should be alright, could do some string processing on the paths to shorten while keeping equal expressivity.
![](https://media.discordapp.net/attachments/855173611409506337/1026595024265289830/unknown.png)

cwd no longer searched for locale files.

2022-10-04 16:25 UTC, LunaTheFoxgirl requested changes
This is not ensured to properly sort strings properly, the suggested change should ensure that.

2022-10-04 16:25 UTC, LunaTheFoxgirl commented on source/creator/core/i18n.d
> +                                                            : (a.humanName < b.humanName));
We'd probably want to use icmp from std.uni so that it properly matches unicode elements such as the German ß, among others.
https://dlang.org/phobos/std_uni.html#icmp

2022-10-05 00:08 UTC, hanss314 commented on source/creator/core/i18n.d
> +                                                            : (a.humanName < b.humanName));
Ah, didn't know about this. Thanks!

2022-10-05 04:20 UTC, LunaTheFoxgirl commented
LGTM

2022-10-05 04:20 UTC, merged